export const ADD_TO_CART = 'ADD_TO_CART';

export const RESET_COUNTER = 'RESET_CART';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const UPDATE_GENERAL_DATA = 'UPDATE_GENERAL_DATA';
